### ISSUE TITLE
询问client配置问题

### ISSUE THREAD

**Issue by AqgRVQEP** [zhxie/ikago#2]
client.json里面pushed ip我是填client ip还是网关ip，还是说就是虚拟ip

**Comment by zhxie** [comment]
Thank you for your interest in IkaGo. You can refer to [client-example.json](https://github.com/zhxie/ikago/blob/master/configs/client-example.json) for configuration. The `-publish` option is the virtual IP address of the device you expect running IkaGo-client, which is also the gateway of the device that needs to be proxied. IkaGo-client will respond to the ARP request to the `-publish` address by proxy ARP, so as to divert the traffic from the source device and proxy it.

------

感谢你对 IkaGo 的关注。你可以参考 [client-example.json](https://github.com/zhxie/ikago/blob/master/configs/client-example.json) 进行配置。`-publish` 选项中应当填写你期望运行 IkaGo-client 的设备的虚拟 IP 地址，这也是需要代理的设备的网关。IkaGo-client 会通过代理 ARP 回应到 `-publish` 地址的 ARP 请求，从而引流来自源设备的流量并进行代理。

**Comment by briteming** [comment]
"期望运行 IkaGo-client 的设备的虚拟 IP 地址",不太明白这句话，你这个程序是全局代理程序吗

**Comment by zhxie** [comment]
@briteming 
IkaGo can pretend to have a designated IP through Proxy ARP to isolate the network of the game console. IkaGo can only be used to proxy other devices in the LAN. It was originally designed to accelerate games on game consoles such as Switch, and IkaGo will proxy all network traffic on the game console.

---

IkaGo 可以通过 Proxy ARP 假装自身拥有指定的 IP，将游戏主机的网络隔离。IkaGo 只能用于代理局域网中的其它设备。其设计初衷是为了加速 Switch 等游戏主机上的游戏，并且 IkaGo 将会代理游戏主机上的所有网络流量。
