### ISSUE TITLE
go get失败

### ISSUE THREAD

**Issue by briteming** [zhxie/ikago#4]
hi.

yudeMacBook-Air:gopath brite$ go get -u -v github.com/zhxie/ikago/cmd/ikago-client/
github.com/zhxie/ikago (download)
github.com/google/gopacket (download)
github.com/sparrc/go-ping (download)
golang.org/x/net (download)
golang.org/x/sys (download)
github.com/xtaci/kcp-go (download)
github.com/klauspost/reedsolomon (download)
github.com/klauspost/cpuid (download)
github.com/pkg/errors (download)
github.com/templexxx/xorsimd (download)
github.com/templexxx/cpu (download)
github.com/tjfoc/gmsm (download)
golang.org/x/crypto (download)

package ikago/internal/addr: unrecognized import path "ikago/internal/addr" (import path does not begin with hostname)
package ikago/internal/config: unrecognized import path "ikago/internal/config" (import path does not begin with hostname)
package ikago/internal/crypto: unrecognized import path "ikago/internal/crypto" (import path does not begin with hostname)
package ikago/internal/exec: unrecognized import path "ikago/internal/exec" (import path does not begin with hostname)
package ikago/internal/log: unrecognized import path "ikago/internal/log" (import path does not begin with hostname)
package ikago/internal/pcap: unrecognized import path "ikago/internal/pcap" (import path does not begin with hostname)
package ikago/internal/stat: unrecognized import path "ikago/internal/stat" (import path does not begin with hostname)
yudeMacBook-Air:gopath brite$

怎么解决？

**Comment by zhxie** [comment]
`go get` downloads dependencies based on the absolute path URL in `import`, but most of IkaGo's internal dependencies are referenced through relative paths. I will try to fix it, but since I personally prefer relative paths, I recommend using `git clone` instead of using `go get` to get the project.

---

`go get` 是根据 import 中的绝对路径 URL 下载依赖的，但是 IkaGo 内部的依赖大多是通过相对路径引用的。我可以尝试修复它，但由于我个人更偏爱相对路径，相比起通过 `go get`，我更推荐使用 `git clone` 来获取项目。

**Comment by briteming** [comment]
我更偏爱用go get来获取项目.麻烦修复import路径。
非常感谢。

**Comment by briteming** [comment]
hi.
你说：“我更推荐使用 git clone 来获取项目”，是这样操作吗：
git clone https://github.com/zhxie/ikago
cd ikago
go install 

谢谢回复

**Comment by zhxie** [comment]
Precisely, after cloning the repository, use build.sh or build.ps1 in the directory to compile the executable file. And after 7b5e59c, this project already supports `go get`.

---

更确切地说，应该是在 clone 这个项目后，使用项目目录中的 build.sh 或 build.ps1 编译获得可执行文件。当然，在 7b5e59c 后，已经可以支持 `go get` 了。
